import type { JimuMapView } from "jimu-arcgis";
import type Extent from "esri/geometry/Extent";
import type FeatureLayer from "esri/layers/FeatureLayer";
import type MediaLayer from "esri/layers/MediaLayer";
import type { AllWidgetProps, React } from "jimu-core";
import type { DebouncedFunc } from "lodash";
import type { PolygonExportImageResult, VegetationIndiceType } from "../../../gis/agri-polygon-api-source";
import type { AgriGraffWidgetState, ConfiguredFilters, RecordData } from "./widget";
import type { GraffWidgetProps, TimerHandle } from "./graff-state";
import type { TaggedLayer } from "./components/spatial-candidates";
import type { ImmutableObject, UseDataSource } from "jimu-core";

/**
 * Widget members the extracted Graff modules read or call.
 * The widget instance is passed as the host.
 */
export interface GraffWidgetHost {
  props: GraffWidgetProps;
  state: AgriGraffWidgetState;
  setState: React.Component<GraffWidgetProps, AgriGraffWidgetState>["setState"];
  _turiToCropId: { [x: string]: string };
  resolveCropIdForTuri: (turi: string) => string | undefined;
  resolveCropIdForUniqueid: (uniqueid: string | null | undefined) => number | null;
  normalizeApos: (s: string) => string;
  makeRegionDistrictKey: (raw: string | null | undefined) => string;
  _viloyatToRegion: { [x: string]: number };
  _tumanToDistrict: { [x: string]: number };
  _tumanToDistrictVotes: { [x: string]: number };
  resolveDistrictNumber: (viloyat: string, tuman: string, regionHint?: number) => number | undefined;
  eqAposSmart: (field: string, raw: string) => string;
  storeRegionDistrictMappingRow: (viloyatRaw: string | null | undefined, regionRaw: unknown, tumanRaw: string | null | undefined, districtRaw: unknown, count?: number) => void;
  graphSvgWrapRef: React.RefObject<HTMLDivElement>;
  _graphViewportRaf: number;
  updateGraphViewportSize: () => void;
  graphResizeObserver: ResizeObserver;
  graphContainerRef: React.RefObject<HTMLDivElement>;
  scheduleGraphViewportRefresh: () => void;
  monthPickerRef: React.RefObject<HTMLDivElement>;
  _isMounted: boolean;
  syncExternalPolygonSelection: (uniqueid: string, polygonMode: boolean, regionIdHint?: number | null, clickedAt?: number) => void;
  _lastSuccessfulOverlayDate: string;
  _lastSuccessfulOverlayRegionId: number;
  _lastSuccessfulOverlayYear: number;
  resolveCurrentRegionId: () => number | undefined;
  resolveCurrentYear: () => number | undefined;
  getCarriedOverlayDate: (regionId: number | undefined, year: number | undefined) => string | null;
  _lastSuccessfulOverlayIndex: "ndvi" | "savi" | "evi" | "rvi" | "ci" | "ndwi" | "ndre";
  _optimisticDateBeforeClear: string;
  _latestRasterDateByUniqueid: Map<string, string>;
  _verifiedOverlayDates: Set<string>;
  beginVegetationImageSurfaceLoading: () => void;
  markOverlayDateVerified: (cleanId: string, date: string) => void;
  applyVegetationImageOverlay: (uniqueid: string, rasterDate: string, indiceType?: VegetationIndiceType, prefetched?: PolygonExportImageResult | null) => Promise<void>;
  _pendingOverlayWalk: { uniqueid: string; promise: Promise<{ date: string; result?: PolygonExportImageResult; } | null>; };
  _mapHoverPrefetchHandle: __esri.Handle;
  _hoverPrefetchTimer: number;
  detachMapHoverPrefetch: () => void;
  prefetchVegetationForMapPoint: (view: __esri.MapView | __esri.SceneView, event: __esri.ViewPointerMoveEvent, regionId: number, year: number) => Promise<void>;
  _hoverPrefetchUniqueid: string;
  rememberRasterDateForUniqueid: (uniqueid: string, dates: string[]) => void;
  _polygonSelectionOrigin: "map" | "table";
  _selectionCommittedAt: number;
  _pendingScrollUniqueid: string;
  _selectionPageResolveToken: number;
  cancelVegetationImageOverlay: () => void;
  _extentBeforeTableSelection: Extent;
  buildWhereClause: () => string;
  fetchRegionalTimeseries: () => Promise<void>;
  fetchData: (opts?: { preservePage?: boolean; }) => Promise<void>;
  _lastMasterFilterBroadcastGeneration: number;
  _lastMasterFilterTs: number;
  _barCategoryField: string;
  _barCategoryValue: string;
  filtersChanged: (a: AgriGraffWidgetState["regionalFilters"], b: AgriGraffWidgetState["regionalFilters"]) => boolean;
  getFeatureLayerForViloyat: (viloyat: string) => __esri.FeatureLayer | undefined;
  publishVegetationOverlayContext: () => void;
  scheduleRefresh: DebouncedFunc<() => Promise<void>>;
  fetchVegetationData: () => Promise<void>;
  resolveFieldCaseInsensitive: (name: string) => string | null;
  getTableSpatialQueryCandidates: () => TaggedLayer[];
  _detachedSpatialQueryLayers: Map<string, FeatureLayer>;
  buildSearchWhere: (raw: string) => string;
  buildTumanNameClause: (tuman: string, viloyat?: string) => string;
  getCategoryFieldName: () => string | null;
  findSpatialFeatureByUniqueId: (uniqueId: string) => Promise<__esri.Graphic | null>;
  addSelectionGlow: (view: __esri.MapView | __esri.SceneView, feature: __esri.Graphic) => void;
  clearSelectionAfterSearchClear: () => Promise<void>;
  handleRowClick: (record: RecordData) => Promise<void>;
  buildVhUniqueIdsClause: () => string;
  buildNdviStatusClauseForCurrentVh: () => string;
  getDisplayFields: () => string[];
  getMaydonSortFieldName: () => string | null;
  getStatusFieldNameForCurrentDate: () => string | null;
  applyMapFilters: () => Promise<void>;
  throttledFetchData: DebouncedFunc<() => Promise<void>>;
  _updateDebounceTimer: TimerHandle | null;
  applyExternalFilterUpdate: (sourceWidget: string, updates: ConfiguredFilters) => Promise<void>;
  tableContainerRef: React.RefObject<HTMLDivElement>;
  normalizeUniqueidKey: (value: string | null | undefined) => string;
  scrollSelectedRowIntoCenter: () => void;
  buildUniqueidWhere: (uniqueid: string) => string;
  RECORDS_PER_PAGE: number;
  recordMatchesUniqueid: (record: RecordData, uniqueid: string) => boolean;
  scheduleScrollSelectedRowIntoCenter: () => void;
  resolveTablePageForUniqueid: (uniqueid: string) => Promise<number | null>;
  initializeMapConnection: (jimuMapView: JimuMapView) => Promise<void>;
  formatFieldValue: (fieldName: string, value: unknown) => string;
  getConfiguredFilterFields: () => string[];
  attachMapHoverPrefetch: (view: __esri.MapView | __esri.SceneView) => void;
  resolveFeatureLayersFromUseDataSources: (jimuMapView: JimuMapView) => Promise<__esri.FeatureLayer[]>;
  fetchAndStoreRegionDistrictMappings: () => Promise<void>;
  buildViloyatKeyToLayerIndex: () => Promise<void>;
  fetchFilterOptions: () => Promise<void>;
  resolveFeatureLayerFromDataSource: (jimuMapView: JimuMapView, useDsOverride?: UseDataSource | ImmutableObject<UseDataSource>) => Promise<__esri.FeatureLayer | null>;
  _viloyatKeyToLayerIndex: { [x: string]: number; };
  MAX_CONNECTION_ATTEMPTS: number;
  retryMapConnection: () => void;
  initializeTheme: () => void;
  refreshFiltersFromConfig: () => void;
  handleThemeChange: (event: CustomEvent<{ isDarkTheme?: boolean; }> | Event) => void;
  handleAppLanguageChanged: (event: Event) => void;
  _unbindMasterFilter: () => void;
  handleMasterFilterChanged: (event: Event) => void;
  _unbindPopupPolygonSelection: () => void;
  handlePopupPolygonSelectionFastPath: (event: Event) => void;
  handleExternalTableSearchChanged: (event: Event) => void;
  handleExternalTableRowSelected: (event: Event) => Promise<void>;
  handleDocumentMouseDown: (event: MouseEvent) => void;
  handleResetAll: () => void;
  handleDateIndexNavigate: (event: Event) => void;
  _onReset: () => void;
  _allowClearOnce: boolean;
  initializationTimer: TimerHandle | null;
  ensureInitialization: () => void;
  observeGraphViewport: () => void;
  _retryTimeout: TimerHandle | null;
  broadcastDateIndexSelection: () => void;
  _activeController: AbortController;
  _debounceTimer: TimerHandle | null;
  _searchDebounceTimer: TimerHandle | null;
  _filterOptionsPromise: Promise<void>;
  fetchFilterOptionsOnce: () => Promise<void>;
  getUniqueValues: (fieldName: string) => Promise<string[]>;
  _hasCompletedTableFetch: boolean;
  _tableDataRequestId: number;
  getTableOrderByFields: () => string[];
  ensureSelectedRowVisible: (uniqueid?: string | null) => Promise<void>;
  refetchDebounced: () => void;
  refetchNow: () => void;
  _hasCompletedGraphFetch: boolean;
  _vegetationDataRequestId: number;
  _regionalTimeseriesRequestId: number;
  _regionalTimeseriesRequestKey: string;
  switchToTable: () => void;
  switchToGraph: () => void;
  isRegionalInteractionEnabled: () => boolean;
  handleToggleAllIndices: () => void;
  handleIndexChange: (index: "ndvi" | "savi" | "rvi" | "ci" | "evi" | "ndwi") => void;
  renderGraphLegend: () => React.JSX.Element;
  renderViewModeToggle: (activeMode: "table" | "graph") => React.JSX.Element;
  renderGraphHeader: () => React.JSX.Element;
  resolveMonthPickerPlacement: () => "up" | "down";
  getNavigableDateIndexDates: () => string[];
  resolveAgainstAvailableDates: (rawDate: unknown, availableDates: string[]) => string | null;
  _vegetationImageRequestId: number;
  removeVegetationImageOverlay: () => void;
  detachVegetationRasterHover: () => void;
  _vegetationRasterSample: { values: Float32Array | null; rgba: Uint8ClampedArray | null; indexMin: number | null; indexMax: number | null; width: number; height: number; xmin: number; ymin: number; xmax: number; ymax: number; spatialReference: __esri.SpatialReference; };
  _vegetationImageLayer: MediaLayer;
  _vegetationOverlayAppliedKey: string;
  _vegetationOverlayPendingKey: string;
  _inSeasonRetryAttempts: Map<string, number>;
  _polygonAvailableDatesUniqueid: string;
  formatLocalDateYmd: (dt: Date) => string;
  onActiveViewChange: (jimuMapView: JimuMapView) => void;
  localizeRuntimeMessage: (value: unknown) => string;
  getFieldDisplayName: (fieldName: string) => string;
  toggleMaydonSort: () => void;
  getStatusValueForRecord: (record: RecordData) => string;
  goToTablePage: (page: number) => void;
  renderGraph: () => React.JSX.Element;
}
