import type { AllWidgetProps, React } from "jimu-core";
import type { JimuMapView } from "jimu-arcgis";
import type { AgriPopupConfig, IMConfig } from "../config";
import type { AgriDashboardState, ChildSuffix } from "./widget";
import type { IndicatorChildPropsSet } from "./AgriMapIndicatorDrawer";

/** Default embedded-panel props: the dashboard's props with a plain config record. */
export type DashboardChildProps = AllWidgetProps<Record<string, unknown>>;

export interface DashboardWidgetHost {
  props: AllWidgetProps<IMConfig>;
  state: AgriDashboardState;
  setState: React.Component<AllWidgetProps<IMConfig>, AgriDashboardState>["setState"];
  syncConfigSideEffects: () => void;
  isBuilderDesignMode: () => boolean;
  setupMapSlotObserver: () => void;
  scheduleMapSlotLayout: (force?: boolean) => void;
  scheduleMapLoadingWatchers: (delay?: number) => void;
  handleMapSurfaceLoading: (event: Event) => void;
  handleMapNoData: (event: Event) => void;
  handleMapPopupVisibility: (event: Event) => void;
  ensurePortalHost: () => HTMLElement;
  syncIndicatorOverlayLayout: () => void;
  ensureLayoutObservers: () => void;
  getActiveMapWidgetId: () => string;
  lastMapWatchWidgetId: string;
  lastIndicatorToggleAt: number;
  indicatorAnimTimer: NodeJS.Timeout;
  dashboardRootRef: React.RefObject<HTMLDivElement>;
  dashboardResizeObserver: ResizeObserver;
  layoutObserversReady: boolean;
  onWindowResize: () => void;
  mapLayoutRaf: number;
  mapSurfaceLoadingSafetyTimer: NodeJS.Timeout;
  detachMapLoadingWatchers: () => void;
  clearIndicatorOverlayLayout: () => void;
  removePortalHost: () => void;
  findSharedLayoutSurface: () => HTMLElement | null;
  portalHost: HTMLElement;
  createPortalHost: () => HTMLElement;
  portalReady: boolean;
  toPlainPopup: (value: unknown) => AgriPopupConfig;
  toPlainConfig: () => Record<string, unknown>;
  indicatorChildPropsCache: IndicatorChildPropsSet & { signature: string };
  childProps: <P = DashboardChildProps>(suffix: ChildSuffix, config?: Record<string, unknown>) => P;
  mapReadyWatchHandle: { remove?: () => void; };
  mapUpdatingWatchHandle: { remove?: () => void; };
  watchedMapView: unknown;
  mapLoadingRetryTimer: NodeJS.Timeout;
  embeddedMapReady: boolean;
  setMapLoading: (mapLoading: boolean) => void;
  getMapLoadingState: (jimuMapView: JimuMapView | null) => boolean;
  getActiveJimuMapView: () => JimuMapView | null;
  mapViewWatchAttempts: number;
  updateMapLoadingState: () => void;
  attachMapLoadingWatchers: () => void;
  getDashboardLoadingState: () => boolean;
  resizeListenerAttached: boolean;
  mapSlotRef: React.RefObject<HTMLElement>;
  lastMapSlotSize: { w: number; h: number; };
  readDashboardCssPx: (variable: string, fallback: number) => number;
  bringPortalHostToFront: () => void;
  mapIndicatorHost: HTMLElement;
  indicatorOverlayRef: React.RefObject<HTMLDivElement>;
  clearOverlayLayout: (overlay: HTMLElement | null) => void;
  applyIndicatorOverlayBounds: (slotEl: HTMLElement, overlayEl: HTMLElement) => void;
  dateIndexOverlayRef: React.RefObject<HTMLDivElement>;
  applyDateIndexOverlayBounds: (slotEl: HTMLElement, overlayEl: HTMLElement) => void;
  forceUpdate: (callback?: () => void) => void;
  getIndicatorConfig: (baseConfig: Record<string, unknown>) => Record<string, unknown>;
  getPopupConfig: (baseConfig: Record<string, unknown>) => Record<string, unknown>;
  getStableIndicatorChildProps: (indicatorConfig: Record<string, unknown>, baseConfig: Record<string, unknown>) => IndicatorChildPropsSet;
  indicatorPanelRef: React.RefObject<HTMLDivElement>;
  toggleIndicatorsDrawer: (event: React.MouseEvent<HTMLButtonElement>) => void;
  getRowFrValues: () => { top: number; bottom: number; };
  getLeftPanelWidth: () => string;
  getUiLanguage: () => string;
}
