import type { AllWidgetProps, React } from "jimu-core";
import type { AgriPopupConfig, IMConfig } from "../config";
import type { AgriDashboardState, ChildSuffix } from "./widget";

export interface DashboardWidgetHost {
  props: AllWidgetProps<IMConfig>;
  state: AgriDashboardState;
  setState: React.Component<any, AgriDashboardState>["setState"];
  syncConfigSideEffects: () => void;
  isBuilderDesignMode: () => boolean;
  setupMapSlotObserver: () => void;
  scheduleMapSlotLayout: (force?: boolean) => void;
  scheduleMapLoadingWatchers: (delay?: number) => void;
  handleMapSurfaceLoading: (event: Event) => void;
  handleMapNoData: (event: Event) => void;
  handleMapPopupVisibility: (event: Event) => void;
  ensurePortalHost: () => HTMLElement;
  syncIndicatorOverlayLayout: () => void;
  ensureLayoutObservers: () => void;
  getActiveMapWidgetId: () => string;
  lastMapWatchWidgetId: string;
  lastIndicatorToggleAt: number;
  indicatorAnimTimer: NodeJS.Timeout;
  dashboardRootRef: React.RefObject<HTMLDivElement>;
  dashboardResizeObserver: ResizeObserver;
  layoutObserversReady: boolean;
  onWindowResize: () => void;
  mapLayoutRaf: number;
  mapSurfaceLoadingSafetyTimer: NodeJS.Timeout;
  detachMapLoadingWatchers: () => void;
  clearIndicatorOverlayLayout: () => void;
  removePortalHost: () => void;
  findSharedLayoutSurface: () => HTMLElement | null;
  portalHost: HTMLElement;
  createPortalHost: () => HTMLElement;
  portalReady: boolean;
  toPlainPopup: (value: unknown) => AgriPopupConfig;
  toPlainConfig: () => Record<string, unknown>;
  indicatorChildPropsCache: { signature: string; indicator: AllWidgetProps<any>; yield: AllWidgetProps<any>; unused: AllWidgetProps<any>; reserve: AllWidgetProps<any>; };
  childProps: (suffix: ChildSuffix, config?: Record<string, unknown>) => AllWidgetProps<any>;
  mapReadyWatchHandle: { remove?: () => void; };
  mapUpdatingWatchHandle: { remove?: () => void; };
  watchedMapView: unknown;
  mapLoadingRetryTimer: NodeJS.Timeout;
  embeddedMapReady: boolean;
  setMapLoading: (mapLoading: boolean) => void;
  getMapLoadingState: (jimuMapView: any | null) => boolean;
  getActiveJimuMapView: () => any | null;
  mapViewWatchAttempts: number;
  updateMapLoadingState: () => void;
  attachMapLoadingWatchers: () => void;
  getDashboardLoadingState: () => boolean;
  resizeListenerAttached: boolean;
  mapSlotRef: React.RefObject<HTMLElement>;
  lastMapSlotSize: { w: number; h: number; };
  readDashboardCssPx: (variable: string, fallback: number) => number;
  bringPortalHostToFront: () => void;
  mapIndicatorHost: HTMLElement;
  indicatorOverlayRef: React.RefObject<HTMLDivElement>;
  clearOverlayLayout: (overlay: HTMLElement | null) => void;
  applyIndicatorOverlayBounds: (slotEl: HTMLElement, overlayEl: HTMLElement) => void;
  dateIndexOverlayRef: React.RefObject<HTMLDivElement>;
  applyDateIndexOverlayBounds: (slotEl: HTMLElement, overlayEl: HTMLElement) => void;
  forceUpdate: (callback?: () => void) => void;
  getIndicatorConfig: (baseConfig: Record<string, unknown>) => Record<string, unknown>;
  getPopupConfig: (baseConfig: Record<string, unknown>) => Record<string, unknown>;
  getStableIndicatorChildProps: (indicatorConfig: Record<string, unknown>, baseConfig: Record<string, unknown>) => { indicator: AllWidgetProps<any>; yield: AllWidgetProps<any>; unused: AllWidgetProps<any>; reserve: AllWidgetProps<any>; };
  indicatorPanelRef: React.RefObject<HTMLDivElement>;
  toggleIndicatorsDrawer: (event: React.MouseEvent<HTMLButtonElement>) => void;
  getRowFrValues: () => { top: number; bottom: number; };
  getLeftPanelWidth: () => string;
  getUiLanguage: () => string;
}
