import type Graphic from "esri/Graphic";
import type FeatureLayer from "esri/layers/FeatureLayer";
import type GraphicsLayer from "esri/layers/GraphicsLayer";
import type { JimuMapView } from "jimu-arcgis";
import type { AllWidgetProps, QueriableDataSource, React } from "jimu-core";
import type { AgriDataSourceEngine } from "../../../gis/agri-data-source-engine";
import type { Config, IHandleLike, State } from "./widget";

export interface PopupWidgetHost {
  props: AllWidgetProps<Config>;
  state: State;
  setState: React.Component<any, State>["setState"];
  POPUP_MARGIN: number;
  POPUP_WIDTH: number;
  isDashboardEmbedded: () => boolean;
  getMapAreaRect: (view: __esri.MapView | __esri.SceneView) => DOMRect;
  DASHBOARD_POPUP_VERTICAL_INSET: number;
  getEffectiveMapBottom: (view: __esri.MapView | __esri.SceneView, gap?: number) => number;
  getPopupWidth: (view?: __esri.MapView | __esri.SceneView | null) => number;
  calculatePinnedPosition: (view: __esri.MapView | __esri.SceneView) => { x: number; y: number; };
  getPinnedPopupHeight: (view: __esri.MapView | __esri.SceneView, topY: number) => number;
  _featureQueryCache: Map<string, { expires: number; value: Promise<__esri.Graphic | null>; }>;
  mapAreaResizeObserver: ResizeObserver;
  schedulePopupLayout: () => void;
  getCropOverlayTop: () => number | null;
  popupPositionsEqual: (a: { x: number; y: number; } | null | undefined, b: { x: number; y: number; }, epsilon?: number) => boolean;
  _isDraggingPopup: boolean;
  _popupLayoutTimer: NodeJS.Timeout;
  repositionPinnedIfNeeded: () => void;
  _popupLayoutRaf: number;
  DASHBOARD_POPUP_HORIZONTAL_INSET: number;
  _isMounted: boolean;
  clampPopupToMapContainer: (pos: { x: number; y: number; }, view: __esri.MapView | __esri.SceneView) => { x: number; y: number; };
  applyPopupPosition: (pos: { x: number; y: number; }) => void;
  calculatePopupPosition: (clickPoint: { x: number; y: number; }, view: __esri.MapView | __esri.SceneView) => { x: number; y: number; };
  schedulePopupLayoutAfterContent: () => void;
  broadcastPopupVisibility: (open: boolean) => void;
  _popupRef: React.RefObject<HTMLDivElement>;
  minimizePopup: () => void;
  _popupDragOffset: { x: number; y: number; };
  onPopupDragMove: (e: MouseEvent) => void;
  onPopupDragEnd: () => void;
  getPopupDimensions: (view?: __esri.MapView | __esri.SceneView | null, pinned?: boolean, position?: { x: number; y: number; } | null) => { width: number; height: number; };
  forceUpdate: () => void;
  _queryOnlyLayers: Map<string, FeatureLayer>;
  pruneFeatureQueryCache: (now?: number) => void;
  getFeatureQueryCacheKey: (layer: __esri.FeatureLayer, oidField: string, oid: unknown, outFields: string[]) => string;
  getDetachedQueryLayer: (layer: any) => Promise<__esri.FeatureLayer | null>;
  _featureQueryCacheTtlMs: number;
  themeObserver: MutationObserver;
  getResolvedTheme: () => boolean;
  _highlightLayer: GraphicsLayer;
  clearHighlight: () => void;
  _highlightHaloGraphic: Graphic;
  _highlightGraphic: Graphic;
  _extentBeforeSelection: __esri.Extent;
  getLinkedMapWidgetId: () => string | null;
  scheduleMapViewFallback: () => void;
  scheduleMapInitRetry: (jmv: JimuMapView) => void;
  getMapViewFromManager: (mapWidgetId: string | null) => JimuMapView | null;
  onActiveViewChange: (jimuMapView: JimuMapView) => void;
  mapViewFallbackTimer: NodeJS.Timeout;
  mapInitRetryCount: number;
  maxMapInitRetries: number;
  mapInitRetryTimer: NodeJS.Timeout;
  initializeMapConnection: (jmv: JimuMapView) => Promise<void>;
  toLiveMapLayer: (layer: any, map: __esri.Map | null | undefined) => __esri.FeatureLayer | null;
  addResolvedLayer: (target: __esri.FeatureLayer[], layerKeyToDsId: Record<string, string>, seen: Set<string>, layer: any, dsId?: string) => void;
  detachMapClick: () => void;
  cleanupHighlight: () => void;
  connectedMapViewId: string;
  tr: (key: string, params?: Record<string, string | number>) => string;
  observeMapAreaResize: (view: __esri.MapView | __esri.SceneView) => void;
  _clickHandle: IHandleLike;
  attachMapClick: (jmv: JimuMapView) => void;
  setupHighlightLayer: (view: __esri.MapView | __esri.SceneView) => void;
  expandUseDataSourceEntries: (useList: any[]) => any[];
  dataSourceEngine: AgriDataSourceEngine;
  snapshotDefinitionExpressions: (layers: Array<__esri.FeatureLayer | any>) => Map<any, string>;
  restoreDriftedDefinitionExpressions: (snapshot: Map<any, string>) => void;
  collectLayersFromDataSources: (jmv: JimuMapView, useList: any[]) => { layers: __esri.FeatureLayer[]; layerKeyToDsId: Record<string, string>; };
  resolveFeatureLayerForUseDataSource: (jmv: JimuMapView, useDs: any) => Promise<__esri.FeatureLayer | null>;
  onViewClick: (ev: __esri.ViewClickEvent) => Promise<void>;
  closePopup: (opts?: { restoreExtent?: boolean; notifyDeselect?: boolean; }) => void;
  _lastMasterGeoKey: string;
  _activeInspectedUniqueid: string;
  openPopupForUniqueid: (uniqueid: string, opts?: { zoom?: boolean; notifySelection?: boolean; }) => Promise<void>;
  expandPopup: () => void;
  _clickGeneration: number;
  resolveClickLayers: (view: __esri.MapView | __esri.SceneView, jmv: JimuMapView) => Promise<__esri.FeatureLayer[]>;
  isAgriculturalFieldLayer: (layer: any) => boolean;
  isLayerEffectivelyVisible: (layer: any, view: __esri.MapView | __esri.SceneView) => boolean;
  getOutFields: (layer: FeatureLayer, oidField: string) => string[];
  queryFeatureByObjectIdCached: (layer: __esri.FeatureLayer, oidField: string, oid: unknown, outFields: string[]) => Promise<__esri.Graphic | null>;
  highlightPolygon: (geometry: __esri.Geometry) => void;
  resolveDisplayAttrs: (polygonAttributes: Record<string, any> | null | undefined) => Promise<Record<string, any>>;
  notifyGraffPolygonSelection: (uniqueid: string, polygonMode: boolean, clickedAt?: number, regionId?: number | null) => void;
  fetchLatestVegetationIndices: (uniqueId: string) => Promise<void>;
  loadAttachmentsForOid: (layer: FeatureLayer, oid: number) => Promise<void>;
  layerKeysMatch: (a: any, b: any) => boolean;
  isHighlightLayer: (layer: any) => boolean;
  isAgriculturalFieldGraphic: (graphic: __esri.Graphic, layer: any) => boolean;
  getClickTargetLayers: (view: __esri.MapView | __esri.SceneView) => __esri.FeatureLayer[];
  toClickQueryGeometry: (view: __esri.MapView | __esri.SceneView, screenPoint: { x: number; y: number; }, mapPoint?: { x?: number; y?: number; spatialReference?: { wkid?: number; }; }) => __esri.Point | null;
  pickClickGraphic: (hit: __esri.HitTestResult | null | undefined, preferredLayers: __esri.FeatureLayer[]) => __esri.Graphic | null;
  _latestIndicesRequestId: number;
  findAttributeValueCaseInsensitive: (attributes: Record<string, any> | null | undefined, fieldName: string) => any;
  resolveClickFeatureAt: (ev: __esri.ViewClickEvent, view: __esri.MapView | __esri.SceneView, layers: __esri.FeatureLayer[]) => Promise<{ graphic: __esri.Graphic; queryHitLayer: __esri.FeatureLayer | null; } | null>;
  restoreExtentBeforeSelection: () => void;
  layerSupportsAttachments: (layer: __esri.FeatureLayer | FeatureLayer | null | undefined) => boolean;
  revokeAllAttachmentUrls: () => void;
  isImageContentType: (ct?: string) => boolean;
  fetchAttachmentPreview: (url: string) => Promise<Blob>;
  getClickedLayer: () => __esri.FeatureLayer | null;
  findFieldMetaOnLayer: (layer: any, fieldName: string) => __esri.Field | null;
  normalizeFieldAlias: (field: any, fallbackName: string) => string;
  resolveFieldName: (key: string) => string | null;
  resolveAliasFromLiveLayers: (fieldName: string) => string | null;
  resolveAliasFromDataSourceSchema: (fieldName: string, ds: any) => string | null;
  isDateField: (name: string) => boolean;
  formatDateSmart: (raw: any) => string;
  setupThemeObserver: () => void;
  handleThemeChange: (e: any) => void;
  handleLanguageChange: (e: any) => void;
  handleOutsideClick: (event: MouseEvent) => void;
  _unbindMasterFilter: () => void;
  handleMasterFilterChanged: (event: Event) => void;
  handleWidgetSelectionChanged: (event: Event) => void;
  handleMapViewReady: (event: Event) => void;
  handleSharedMapClick: (event: Event) => Promise<void>;
  handleXyPageClosed: () => void;
  mapClickBootstrapTimer: NodeJS.Timeout;
  ensureMapClickAttached: () => boolean;
  getFieldAlias: (name: string) => string;
  niceChartMax: (value: number) => number;
  formatChartTick: (value: number) => string;
  buildRoundedBarPath: (x: number, y: number, width: number, height: number, radius: number) => string;
  setChartHover: (index: number) => void;
  buildSmoothLinePath: (points: Array<{ x: number; y: number; }>) => string;
  clearChartHover: () => void;
  formatChartTooltipValue: (value: number) => string;
  toggleChartExpanded: () => void;
  renderChartIcon: (type?: "bar" | "line") => JSX.Element;
  onPopupHeaderMouseDown: (e: React.MouseEvent<HTMLDivElement>) => void;
  togglePinToCorner: () => void;
  formatValue: (name: string, raw: any) => string;
  renderLatestIndices: () => React.JSX.Element;
  renderChart: () => React.JSX.Element;
  bytesToSize: (n?: number) => string;
  renderPopup: () => React.JSX.Element;
  onDataSourceCreated: (ds: QueriableDataSource) => void;
}
