import type { DataSourceManager, IMUseDataSource, React } from "jimu-core";
import type { AllWidgetSettingProps } from "jimu-for-builder";
import type { AgriPopupConfig, IMConfig } from "../config";
import type { FieldInfo, State } from "./agri-popup-setting";

export interface PopupSettingHost {
  props: AllWidgetSettingProps<IMConfig>;
  state: State;
  setState: React.Component<any, State>["setState"];
  initializeDataSources: () => Promise<void>;
  onPopupFieldMenuOutside: (event: MouseEvent) => void;
  getUseDataSourceKey: (value: unknown) => string;
  getAgriConfig: () => AgriPopupConfig;
  placePopupFieldMenu: () => void;
  detachPopupFieldMenuListeners: () => void;
  cleanupDataSources: () => void;
  popupFieldButtonRef: React.RefObject<HTMLButtonElement>;
  popupMenuFrame: { top: number; left: number; width: number; maxHeight: number; };
  popupFieldMenuRef: React.RefObject<HTMLDivElement>;
  popupFieldListRef: React.RefObject<HTMLUListElement>;
  toPlainAgri: (value: unknown) => AgriPopupConfig;
  ensureDashboardConfig: () => IMConfig;
  updateAgriConfig: (patch: Partial<AgriPopupConfig>) => void;
  mergeFieldOrder: (fields: FieldInfo[], saved: string[]) => string[];
  orderedPopupFieldNames: () => string[];
  commitPopupFields: (fieldsToShow: string[], fieldOrder: string[]) => void;
  formatFieldLabel: (f: FieldInfo) => string;
  popupFieldDragFrom: number;
  reorderPopupOptions: (from: number, to: number) => void;
  togglePopupField: (name: string) => void;
  lastUseDataSourceKey: string;
  createDataSources: (useList: IMUseDataSource[]) => Promise<void>;
  releaseOwnedDataSources: () => void;
  ownedDataSourceIds: string[];
  dsMgr: DataSourceManager;
  extractFieldsFromDs: () => Promise<void>;
  resolveLayerFromDataSource: (ds: any) => Promise<any | null>;
  fieldsExtractToken: number;
  fieldsFromSchemaObject: (fieldsObj: Record<string, any>) => FieldInfo[];
  fieldsFromLayer: (layer: any) => FieldInfo[];
  renderPopupFieldSelect: (fieldsToShow: string[]) => React.JSX.Element;
  onChartEnabledToggle: (e: any) => void;
  onChartTypeChange: (e: any) => void;
  onChartTitleChange: (val: string) => void;
  renderFieldsMultiSelect: (selectedItems: string[], onItemClick: (evt: React.MouseEvent, value: string | number, selectedValues: Array<string | number>) => void, placeholder: string, options?: { menuZIndex?: number; selectKey?: string; }) => React.JSX.Element;
  onChartFieldsMultiSelect: (_evt: React.MouseEvent, _value: string | number, selectedValues: Array<string | number>) => void;
  onChartColorChange: (color: string) => void;
  onZoomToggle: (e: any) => void;
  onPopupToggle: (e: any) => void;
  onAttachmentsToggle: (e: any) => void;
  forceUpdate: (callback?: () => void) => void;
}
