import type { JimuMapView } from "jimu-arcgis";
import type { AllWidgetProps, DataSource, React } from "jimu-core";
import type { DebouncedFunc } from "lodash";
import type { IndicatorConfig, VegetationStatsWidgetState } from "./widget";
import type { IndicatorCustomStyles } from "./components/indicator-data/indicator-style";

export interface IndicatorWidgetHost {
  props: AllWidgetProps<IndicatorConfig>;
  state: VegetationStatsWidgetState;
  setState: React.Component<AllWidgetProps<IndicatorConfig>, VegetationStatsWidgetState>["setState"];
  _isMounted: boolean;
  _isResetting: boolean;
  getFieldType: (name: string) => string | null;
  normalizeUzbekForApi: (s: string) => string;
  makeApostropheVariants: (s: string) => string[];
  _vhJoinSource: string[];
  _vhJoinExpanded: string[];
  fetchApiData: () => Promise<void>;
  _unbindMasterFilter: () => void;
  handleMasterFilterChanged: (event: Event) => void;
  _onReset: () => void;
  readFiltersFromUrl: () => void;
  setupAutoRefresh: () => void;
  initializeTheme: () => void;
  handleThemeChange: (event: Event) => void;
  _containerRef: React.RefObject<HTMLDivElement>;
  _resizeObserver: ResizeObserver;
  initializationTimer: ReturnType<typeof setTimeout> | null;
  ensureInitialization: () => void;
  _lastMasterFilterBroadcastGeneration: number;
  _lastMasterFilterTs: number;
  normalizeTurlar: (raw: unknown, fallback?: string) => string[];
  prepareVhJoinIds: (ids: string[] | null) => Promise<void>;
  _lastFilterEventMs: number;
  _canonicalFeatureLayer: __esri.FeatureLayer;
  getDefaultFeatureLayer: (layersOverride?: __esri.FeatureLayer[]) => __esri.FeatureLayer | undefined;
  refreshData: () => void;
  throttledFetchData: DebouncedFunc<(forceRefresh?: boolean) => Promise<void>>;
  refreshTimer: ReturnType<typeof setInterval> | null;
  _abortController: AbortController;
  MAX_CONNECTION_ATTEMPTS: number;
  shouldFetchForViloyat: () => boolean;
  fetchData: (_forceRefresh?: boolean) => Promise<void>;
  retryMapConnection: () => void;
  initializeMapConnection: (jimuMapView: JimuMapView) => Promise<void>;
  makeViloyatKeyForRouting: (viloyat: string) => string;
  _viloyatKeyToLayerIndex: { [x: string]: number; };
  isRepublicLayer: (layer?: __esri.FeatureLayer) => boolean;
  _mapConnectionPromise: Promise<void>;
  initializeMapConnectionOnce: (jimuMapView: JimuMapView) => Promise<void>;
  buildViloyatLayerIndex: (layers: __esri.FeatureLayer[]) => Promise<void>;
  buildTurlarClause: (field: string, values: string[]) => string;
  fetchGroupedFirst: (featureLayer: __esri.FeatureLayer, groupField: string, valueField: string, _outName: string) => Promise<void>;
  _requestId: number;
  buildWhereClause: (includeViloyat?: boolean) => string;
  nz: (field: string) => string;
  labelNoValue: () => string;
  buildApiUrl: () => string;
  makeDistrictSuffixVariants: (raw: string) => string[];
  makeRegionSuffixVariants: (raw: string) => string[];
  fetchGroupedStats: () => Promise<void>;
  getFeatureLayerForViloyat: (viloyat: string, layersOverride?: __esri.FeatureLayer[]) => __esri.FeatureLayer | undefined;
  getCustomStyles: () => IndicatorCustomStyles;
  onDataSourceCreated: (dataSource: DataSource) => void;
  onDataSourceInfoChange: (info: unknown) => void;
  onActiveViewChange: (jimuMapView: JimuMapView) => void;
  translateKnownError: (msg: string) => string;
}
