import type { JimuMapView } from "jimu-arcgis";
import type { DataSource, React } from "jimu-core";
import type { AgriCropLanguage } from "../../../shared/agri-crop-labels";
import type { AgriPieProps, AgriPieState } from "./widget";

export interface PieWidgetHost {
  props: AgriPieProps;
  state: AgriPieState;
  setState: React.Component<any, AgriPieState>["setState"];
  fetchCategoryData: () => void;
  _isMounted: boolean;
  findFieldByPossibleNames: (possibleNames: string[]) => string | null;
  cropIdsToTuriNames: (ids: string[]) => string[];
  _cropMapsReady: boolean;
  _cropIdToTuri: { [x: string]: string; };
  _turiToCropId: { [x: string]: string; };
  normalizeName: (s: string) => string;
  resolveCropIdToTuri: (cropId: string) => string;
  resolveTuriToCropId: (turi: string) => string;
  makeAposVariants: (s: string) => string[];
  isRepublicLayer: (layer?: __esri.FeatureLayer) => boolean;
  makeViloyatKey: (raw: string | null | undefined) => string;
  _viloyatKeyToLayerIndex: { [x: string]: number; };
  getFeatureLayerForViloyat: (viloyat: string) => __esri.FeatureLayer | undefined;
  getDefaultFeatureLayer: (layersOverride?: __esri.FeatureLayer[]) => __esri.FeatureLayer | undefined;
  _featureLayersInitPromise: Promise<void>;
  resolveFeatureLayersFromUseDataSources: () => Promise<__esri.FeatureLayer[]>;
  buildViloyatKeyToLayerIndex: (layers: __esri.FeatureLayer[]) => Promise<void>;
  CONNECTION_TIMEOUT_MS: number;
  _didInitOnce: boolean;
  waitForMapToLoad: (jimuMapView: JimuMapView) => Promise<void>;
  connectToMap: (jimuMapView: JimuMapView) => Promise<void>;
  initializeAfterConnection: () => void;
  ensureCropIdMaps: () => Promise<void>;
  handleMasterFilterChange: (event: Event) => void;
  turiNamesToCropIds: (names: string[]) => string[];
  initializeTheme: () => void;
  _unbindMasterFilter: () => void;
  handleThemeToggled: (event: Event) => void;
  handleResize: () => void;
  updatePieChart: (reason?: "data" | "selection") => void;
  findAreaStatisticField: (fl: __esri.FeatureLayer) => string | null;
  updateFiltersFromProps: (filters: { yil?: string; viloyat?: string; tuman?: string; turi?: string; }) => void;
  MAX_CONNECTION_ATTEMPTS: number;
  _fetchDebounceTimer: any;
  detachPieResizeObserver: () => void;
  _pieChart: echarts.ECharts;
  _pieChartHostEl: HTMLDivElement;
  _pieHasRendered: boolean;
  _pieStableKeys: string[];
  _pieStableRawKeys: { [x: string]: string; };
  _pieResizeRaf: number;
  _pieResizeObserver: ResizeObserver;
  _pieObservedStage: Element;
  schedulePieChartResize: () => void;
  isIpadLayout: () => boolean;
  _lastIpadLayout: boolean;
  getCategoryDisplayName: (rawKey: string, language: AgriCropLanguage) => string;
  _pieChartRef: React.RefObject<HTMLDivElement>;
  handleSliceClick: (data: { rawKey?: string; name?: string; }, index: number) => void;
  attachPieResizeObserver: (host: HTMLDivElement) => void;
  getCenterAllLabel: () => string;
  ensurePieChart: () => any;
  getChartDataForPie: () => { name: any; rawKey: string; value: number; percentage: number; }[];
  getSliceBorderColor: () => string;
  getCropColor: (rawKey: string, index: number) => string;
  resolveNdviDateForVhPie: () => string;
  resolveRegionDistrictForPie: () => Promise<{ region?: number; district?: number; }>;
  _fetchCounter: number;
  _hasCompletedFetch: boolean;
  _doFetchCategoryData: () => Promise<void>;
  makeQueryKey: (yil: string, viloyat: string, tuman: string, vh: string, barField?: string | null, barValue?: string | null, filterPieByVh?: boolean, pieVhSig?: string, ndviDate?: string) => string;
  _lastFetchKey: string;
  _pendingVhPieFetchKey: string;
  findCategoryField: (flOverride?: __esri.FeatureLayer | null) => string | null;
  fetchPieCategoriesViaVegetation: (fetchId: number) => Promise<boolean>;
  buildWhereClauseForDS: (opts?: { includeCategory?: boolean; includeViloyat?: boolean; districtCode?: number | null; }) => string;
  buildPieVhWhereChunks: (idsOverride?: string[] | null) => string[] | null;
  queryCategoryStatsJSON: (fl: __esri.FeatureLayer, where: string, categoryField: string) => Promise<Array<{ key: string; value: number; }>>;
  forceUpdate: () => void;
  onDataSourceCreated: (ds: DataSource) => void;
  onDataSourceInfoChange: (info: any) => void;
  onActiveViewChange: (jimuMapView: JimuMapView) => Promise<void>;
  retryMapConnection: () => void;
  renderRadarPieChart: (_chartData: any[], _containerWidth?: number, _containerHeight?: number) => JSX.Element;
  getPieCenterContent: (chartData: Array<{ name: string; rawKey?: string; value: number; percentage?: number; }>) => { showPercent: boolean; percent: number; area: number; label: string; };
  formatCenterPercent: (value: number) => string;
  formatCenterArea: (value: number) => string;
}
